{{- if .Values.networkpolicysetting.enabled }}
# Allow nginx-ingress in-bound traffic
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nginx-ingress
spec:
  podSelector:
    matchLabels:
      app: nginx-ingress
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - {}
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        # Block accessing EC2 metadata
        - 169.254.169.254/32
{{- end }}