# Defines the service for the alfresco share app
apiVersion: v1
kind: Service
metadata:
  name: {{ template "content-services.fullname" . }}-share
  labels:
    app: {{ template "content-services.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: share
spec:
  type: {{ .Values.share.service.type }}
  ports:
    - port: {{ .Values.share.service.externalPort }}
      targetPort: {{ .Values.share.image.internalPort }}
      name: {{ .Values.share.service.name }}
  selector:
    app: {{ template "content-services.fullname" . }}-share
    release: {{ .Release.Name }}